// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: AboutctrlCtrl', function() {
    var AboutctrlCtrl, scope;
    beforeEach(module('fullpageApp'));
    AboutctrlCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return AboutctrlCtrl = $controller('AboutctrlCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=about.map
*/
