// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: AppctrlCtrl', function() {
    var AppctrlCtrl, scope;
    beforeEach(module('fullpageApp'));
    AppctrlCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return AppctrlCtrl = $controller('AppctrlCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
