// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: ContactctrlCtrl', function() {
    var ContactctrlCtrl, scope;
    beforeEach(module('fullpageApp'));
    ContactctrlCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return ContactctrlCtrl = $controller('ContactctrlCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=contact.map
*/
