// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  describe('Controller: PlatformctrlCtrl', function() {
    var PlatformctrlCtrl, scope;
    beforeEach(module('fullpageApp'));
    PlatformctrlCtrl = {};
    scope = {};
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return PlatformctrlCtrl = $controller('PlatformctrlCtrl', {
        $scope: scope
      });
    }));
    return it('should attach a list of awesomeThings to the scope', function() {
      return expect(scope.awesomeThings.length).toBe(3);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=platform.map
*/
